import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';

const html = readFileSync(new URL('../index.html', import.meta.url), 'utf8');
const sw = readFileSync(new URL('../sw.js', import.meta.url), 'utf8');

assert.match(html, /key: 'arco'/);
assert.match(html, /name: 'Arco y flechas'/);
assert.match(html, /bow: true/);
assert.match(html, /function makeVoxelBow\(/);
assert.match(html, /function makeArrowMesh\(/);
assert.match(html, /flying = false/);
assert.match(html, /userData.flyingArrow/);
assert.match(html, /makeArrowMesh\(1, true\)/);
assert.match(html, /name = 'flyTrail'/);
assert.match(html, /function arrowHitFeedback\(/);
assert.match(html, /toast\('🏹 Le pegaste'\)/);
assert.match(html, /hitEnemy\(e, dmg, pos, true\)/);
assert.match(html, /function applyMonsterKnock\(/);
assert.match(html, /ud\.knockT = 0\.38/);
assert.match(html, /function tickHitStagger\(/);
assert.match(html, /function shootBowArrow\(/);
assert.match(html, /function updatePlayerArrows\(/);
assert.match(html, /function updateBow\(/);
assert.match(html, /function startBowDraw\(/);
assert.match(html, /function releaseBow\(/);
assert.match(html, /function bowEquipped\(/);
assert.match(html, /n.includes\('arco'\) \? 'bow'/);
assert.match(html, /kind === 'bow' \? makeVoxelBow/);
assert.match(html, /id="bowcharge"/);
assert.match(html, /hasBow: false/);
assert.match(html, /hasBow: !!state\.hasBow/);
assert.match(html, /startBowDraw\('key'\)/);
assert.match(html, /bowDrawSrc === 'key'/);
assert.match(html, /ud\.vel\.y -= grav \* dt/);
assert.match(html, /speed = 16 \+ 38 \* power/);
assert.match(html, /function bowArrowDamage\(/);
assert.match(html, /function arrowHitsBody\(/);
assert.match(html, /function hitFloatingCitizenAt\(/);
assert.match(html, /function renderBowDamageHud\(/);
assert.match(html, /id="bowdmg"/);
assert.match(html, /Daño del arco: tensado bajo 9, medio 12 y máximo 18/);
assert.match(html, /hitFloatingCitizenAt\(pos, dmg\)/);
assert.match(html, /Mantén para tensar el arco/);
assert.match(html, /item\.bow \|\| item\.key === 'arco'/);
assert.match(html, /clearPlayerArrows\(\)/);
assert.doesNotMatch(html, /if \(e\.code === 'KeyE'\) \{ const alexaTarget=e\.shiftKey&&aimedFurniture\(\);if\(alexaTarget&&alexaTarget\.key==='alexa'\)\{useAlexaText\(alexaTarget\);return;\}if \(!tryRefuelCar/);
assert.match(html, /function selectHandTool\(/);
assert.match(html, /function equipHandWeapon\(/);
assert.match(html, /function rememberMeleeWeapon\(/);
assert.match(html, /function storedMeleeIsReal\(/);
assert.match(html, /function sanitizeWeaponPockets\(/);
assert.match(html, /function laserEquipped\(/);
assert.match(html, /function laserShopItem\(/);
assert.match(html, /slot1TapAt/);
assert.match(html, /slot1DupAt/);
assert.match(html, /now - slot1DupAt < 35/);
assert.match(html, /dos toques seguidos = arco/);
assert.match(html, /selectSlot\(1, 'wheel'\)/);
assert.match(html, /meleeName: state\.meleeName/);
assert.match(html, /lastNonBow: state\.lastNonBow/);
assert.match(html, /k === 'bow' \|\| k === 'fist' \|\| k === 'gun'/);
assert.match(html, /if \(state\.laserGun\) return equipHandWeapon\('gun'\)/);
assert.match(html, /if \(item\.key === 'laserpistol'\)/);
assert.match(html, /if \(bowEquipped\(\) \|\| laserEquipped\(\)\) \{/);
assert.match(html, /sanitizeWeaponPockets\(\)/);
assert.match(sw, /tim-v56/);

console.log('bow and arrow: ok');
