import assert from 'node:assert/strict';
import vm from 'node:vm';
import { readFileSync } from 'node:fs';
const html = readFileSync(new URL('../index.html', import.meta.url), 'utf8');
const position = { x: 0, y: 0, z: 0, copy(p) { Object.assign(this, { x:p.x, y:p.y, z:p.z }); }, set(x,y,z) { Object.assign(this,{x,y,z}); } };
const butler = { position, rotation: {}, userData: { task:'idle', order:null } };
const state = { running: true, planet:'tierra', money:1000, inv:{food:0} };
let answer = '', message = '';
const context = vm.createContext({ butler, state, typing:false, BUTLER_HOME:{x:0,z:0}, BUTLER_SUPER:{x:40,z:-31}, butlerSpaceTaps:[], mountainHeightAt:()=>0, releaseLock(){}, prompt:()=>answer, toast:t=>{message=t;}, saveGame(){}, tone(){}, setTimeout(){}, swingLimbs(){}, dist2D:(a,b)=>Math.hypot(a.x-b.x,a.z-b.z), moveToward(e,t,step){const d=Math.hypot(t.x-e.position.x,t.z-e.position.z);e.position.x+=(t.x-e.position.x)*step/d;e.position.z+=(t.z-e.position.z)*step/d;} });
vm.runInContext(html.slice(html.indexOf('const STORE_A ='),html.indexOf('// Mayordomo:')), context);
vm.runInContext(html.slice(html.indexOf('function normalizeButlerText'),html.indexOf('function payButlerDailyWage')), context);
vm.runInContext(html.slice(html.indexOf('function buyItem(item)'),html.indexOf('function setWeaponColor')), context);
const run = code => vm.runInContext(code,context);
const order = text => {answer=text;run('requestButlerOrder()');};
order('ve al supermercado y compra 3 paredes de madera');
assert.equal(state.money,820);assert.equal(butler.userData.order.qty,3);
order('compra 2 techos'); assert.equal(butler.userData.order.item.key,'wallWood','no reemplazar encargos pendientes');
state.money=0; // El jugador gastó todo su saldo disponible durante el trayecto.
for(let i=0;i<400;i++) run('updateButler(.05)');
assert.equal(state.inv.wallWood,3,'compra con dinero reservado aunque el saldo esté vacío');
assert.equal(state.money,0,'no cobrar dos veces');
for(let i=0;i<400;i++) run('updateButler(.05)');
assert.equal(butler.userData.order,null);
state.money=1000;order('compra papas en el supermercado');
assert.equal(butler.userData.order.item.key,'papas','no confundir papas con arma para papá');
const saved = JSON.parse(JSON.stringify({task:butler.userData.task,x:position.x,z:position.z,order:{key:'papas',qty:1,reserved:70,bought:0}}));
context.saved=saved;run('restoreButler(saved)');
position.copy({x:40,z:-31});run('updateButler(.05)');assert.equal(state.inv.food,1);
assert.equal(state.money,930);
context.saved={...saved,task:'return',order:{...saved.order,reserved:0,bought:1}};
run('restoreButler(saved)');position.copy({x:0,z:0});run('updateButler(.05)');
assert.equal(state.inv.food,1,'cargar regreso no duplica compras');
order('compra cosas para la casa en el supermercado');assert.equal(butler.userData.task,'idle');assert.match(message,/No reconocí/);
order('compra comida y carne');assert.equal(butler.userData.order,null);assert.match(message,/un producto por viaje/);
order('compra 3 cocas');assert.equal(butler.userData.order.item.key,'coca');
run('resetButler()');state.money=10;order('compra 2 techos');assert.equal(butler.userData.order,null);
assert.ok(html.includes('restoreButler(d.butlerState)'));
assert.ok(html.includes('butlerState: { task: butler.userData.task'));
console.log('butler: ok');
