import assert from 'node:assert/strict';
import vm from 'node:vm';
import {readFileSync} from 'node:fs';
const html=readFileSync(new URL('../index.html',import.meta.url),'utf8');
const make=(x=0)=>({visible:true,position:{x,z:0},userData:{hp:100,maxHp:100}});
const child=make(),dog=make(),alien=make(),egg=make();let saves=0,clears=0,dadDamage=0;
const c=vm.createContext({helpers:[child],pet:dog,petAlien:alien,eggPets:[egg],state:{creative:false,helperArmor:false},player:{position:{}},dad:{position:{}},scene:{remove(){}},floatText(){},toast(){},saveGame(){saves++;},removePet(){c.pet=null;},removeAlienPet(){c.petAlien=null;},clearPetPoint(){clears++;},damageDad(n){dadDamage+=n;},damagePlayer(){},applyPoison(){},dist2D:(a,b)=>Math.hypot(a.x-b.x,a.z-b.z)});
vm.runInContext(html.slice(html.indexOf('function livingCompanions()'),html.indexOf('function pickTarget(')),c);
c.target=child.position;vm.runInContext('damageEnemyTarget(target,20,{})',c);
assert.equal(child.userData.hp,80);assert.equal(dadDamage,0,'golpear un hijo no daña al papá');
c.state.helperArmor=true;vm.runInContext('damageEnemyTarget(target,20,{})',c);assert.equal(child.userData.hp,70);
c.state.creative=true;vm.runInContext('damageEnemyTarget(target,999,{})',c);assert.equal(child.userData.hp,70);
c.state.creative=false;vm.runInContext('damageEnemyTarget(target,200,{})',c);assert.equal(c.helpers.length,0);assert.equal(saves,1);
vm.runInContext('damageEnemyTarget(target,200,{})',c);assert.equal(saves,1,'sin muerte duplicada');
vm.runInContext('damageCompanionsInRadius({x:0,z:0},4.5,100)',c);assert.equal(c.pet,null);assert.equal(c.petAlien,null);assert.equal(c.eggPets.length,0);assert.equal(clears,1);assert.equal(saves,4);
c.restored=make();vm.runInContext('initCompanionHealth(restored,120,35)',c);assert.equal(c.restored.userData.hp,35);
vm.runInContext('initCompanionHealth(restored,120)',c);assert.equal(c.restored.userData.hp,120,'partidas antiguas cargan vida completa');
assert.ok(html.includes('petHp: pet?.userData.hp'));
assert.ok(html.includes('makeHelperAt(h.x, h.z, h.hp)'));
assert.ok(html.includes('damageCompanion(companion, ud.dmg)'));
console.log('companion health: ok');
