import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';

const html = readFileSync(new URL('../index.html', import.meta.url), 'utf8');
assert.match(html, /function buildIslandTemple\(/);
assert.match(html, /function worldWestLimit\(\)/);
assert.match(html, /function noteIslandArrival\(/);
assert.match(html, /function syncIslandSurfaceDecor\(\)/);
assert.match(html, /function mineFloorY\(/);
assert.match(html, /Se abrió el piso de lava/);
assert.match(html, /Llegaste volando a la ISLA DEL TESORO/);
assert.match(html, /wasIsland \? TREASURE_ISLAND\.surface/);
assert.match(html, /islandTempleAt\(player\.position\.x, player\.position\.z\)/);
assert.match(html, /!state\.underground && inTreasureIsland/);
assert.match(html, /state\.underground \|\| !inTreasureIsland/);
assert.match(html, /state\.groundY = mineFloorY\(fallHole\)/);
assert.match(html, /oreY=mineFloorY\(h\)\+\.7/);
assert.match(html, /islandTempleGroups\.push\(temple\)/);
assert.match(html, /for \(const t of islandTempleGroups\) t\.visible = show/);
assert.match(html, /tryIslandTempleChest\(\) && !tryFocusedFurniture/);
assert.match(html, /onIsland\) \{ scene\.fog\.near \+= \(40 - scene\.fog\.near\)/);
assert.match(html, /scene\.fog\.far \+= \(800 - scene\.fog\.far\)/);
assert.match(html, /function debugTreasureIsland\(/);
assert.doesNotMatch(html, /copas densas y oscuras/);
assert.doesNotMatch(html, /islandShade \? \.78/);
assert.match(html, /Golpea las vetas · E sale de la mina/);
assert.match(html, /Abrir el cofre del templo/);
console.log('island temples: ok');
