import assert from 'node:assert/strict';
import vm from 'node:vm';
import { readFileSync } from 'node:fs';
const html = readFileSync(new URL('../index.html', import.meta.url),'utf8');
const dog = {}, alien = {}, common = {userData:{tier:'común'}}, legendary = {userData:{tier:'LEGENDARIA'}};
let saves = 0, flags = 0, nearby = true;
const c = vm.createContext({ pet:dog, petAlien:alien, eggPets:[common,legendary], EGG_RANK:{'común':0,LEGENDARIA:4}, EGG_TIERS:[{tier:'común'},{},{},{},{tier:'legendario'}], state:{running:true,money:0}, shopSellMode:true, nearKeeper:()=>nearby, removePet(){c.pet=null;},removeAlienPet(){c.petAlien=null;},scene:{remove(){}},clearPetPoint(){flags++;},addMoney(n){c.state.money+=n;},saveGame(){saves++;},toast(){},renderShopList(){},ui:()=>({value:''}) });
vm.runInContext(html.slice(html.indexOf('function petSaleOffers()'),html.indexOf('function renderPetSaleRows')),c);
const sell = animal => {c.selected=animal;return vm.runInContext('sellPet(selected)',c);};
assert.equal(sell(dog),true);assert.equal(c.state.money,1250);assert.equal(c.pet,null);
assert.equal(sell(dog),false,'doble clic no duplica dinero');
assert.equal(sell(alien),true);assert.equal(c.state.money,2350);assert.equal(c.petAlien,null);
nearby=false;assert.equal(sell(common),false);nearby=true;
c.shopSellMode=false;assert.equal(sell(common),false);c.shopSellMode=true;
assert.equal(sell(common),true);assert.equal(flags,0,'mantener bandera si quedan mascotas');
assert.equal(c.eggPets[0],legendary,'vender exactamente la mascota seleccionada');
assert.equal(sell(legendary),true);assert.equal(c.state.money,6600);assert.equal(flags,1);assert.equal(c.eggPets.length,0);assert.equal(saves,4);
assert.equal(sell(legendary),false);
console.log('pet sales: ok');
