import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';
const html = readFileSync(new URL('../index.html', import.meta.url), 'utf8');
assert.match(html, /GAS_STATION_POS/);
assert.match(html, /GAS_STATION_POS = new THREE\.Vector3\(LUGARES\.gasolinera\.x, 0, LUGARES\.gasolinera\.z\)/);
assert.match(html, /icon\(GAS_STATION_POS\.x, GAS_STATION_POS\.z, '⛽'/);
assert.match(html, /icon\(ARCADE_POS\.x, ARCADE_POS\.z, '🎮'/);
assert.match(html, /const target = state\.driving \? car : vehicles\.find/);
assert.match(html, /Compraste ' \+ missing/);
assert.match(html, /car\.fuel = Math\.max\(0, car\.fuel - Math\.abs\(move\) \* \.035\)/);
assert.match(html, /const cost = missing \* 3/);
assert.match(html, /fuel: v\.fuel/);
assert.match(html, /ARCADE_POS/);
for (const game of ['Pac-Man', 'Carrera Turbo', 'Invasores espaciales', 'Baile con luces', 'Pesca de premios']) assert.match(html, new RegExp(game));
assert.match(html, /state\.arcadeTickets = \(state\.arcadeTickets \|\| 0\) \+ s\.game\.tickets/);
assert.match(html, /const ARCADE_GAMES = \[/);
assert.match(html, /function openArcadeMini\(game\)/);
assert.match(html, /if \(game\.name === 'Pac-Man'\) return pacOpen\(true\)/);
assert.match(html, /¡Ganaste Pac-Man! \+50 tickets/);
assert.match(html, /arcadeGameAction/);
assert.match(html, /const PLAY_GAMES = \[/);
assert.match(html, /id: 'futbol'/);
assert.match(html, /id: 'granprix'/);
assert.match(html, /id: 'heroes'/);
assert.match(html, /id: 'carrera'/);
assert.match(html, /id: 'invasores'/);
assert.match(html, /id: 'baile'/);
assert.match(html, /id: 'pesca'/);
assert.match(html, /id="miniGameCanvas"/);
assert.match(html, /function openPlayStation\(\)/);
assert.match(html, /function playHasTv\(/);
assert.match(html, /function nearestPlayNear\(/);
assert.match(html, /Pon una tele en la mesa para jugar a la Play/);
assert.match(html, /Pon una Play en la mesa para jugar/);
assert.match(html, /'play_gamer', 'tele'/);
assert.match(html, /function miniStep\(dt\)/);
assert.match(html, /function startCarrera\(game\)/);
assert.match(html, /function startInvasores\(game\)/);
assert.match(html, /function startBaile\(game\)/);
assert.match(html, /function startPesca\(game\)/);
assert.match(html, /function startFutbol\(game\)/);
assert.match(html, /function startGranPrix\(game\)/);
assert.match(html, /function startHeroes\(game\)/);
assert.match(html, /function gpOnAsphalt\(/);
assert.match(html, /function drawMiniCar\(/);
assert.match(html, /lives: 3/);
assert.match(html, /if \(target\.key === 'play_gamer' \|\| target\.key === 'tele'\) return openPlayStation\(\)/);
assert.doesNotMatch(html, /arcadeMiniAction/);
assert.match(html, /function trySeatedPlay\(\)/);
const sw = readFileSync(new URL('../sw.js', import.meta.url), 'utf8');
assert.match(sw, /tim-v48/);
assert.match(html, /ARCADE_REWARDS_POS/);
assert.match(html, /CANJE DE PREMIOS/);
assert.match(html, /function tryArcadeRewards\(\)/);
assert.match(html, /state\.arcadePrizes\[reward\.id\]/);
assert.match(html, /arcadePrizes: state\.arcadePrizes \|\| \{\}/);
assert.match(html, /tryRefuelCar\(\)/);
assert.match(html, /tryArcadeZone\(\)/);
console.log('vehicles and arcade: ok');

assert.match(html, /const ARCADE_MACHINES = \[\]/);
assert.match(html, /ARCADE_MACHINES\.push/);
assert.match(html, /if \(!machine\) return false/);
assert.match(html, /ARCADE_POS = new THREE\.Vector3\(LUGARES\.arcade\.x, 0, LUGARES\.arcade\.z\)/);
assert.match(html, /const roof = new THREE\.Mesh\(new THREE\.BoxGeometry\(34, \.4, 28\)/);
assert.match(html, /entrada central de 10 unidades/);
assert.match(html, /const wallMat = mat\(0x17133d\)/);
assert.match(html, /const landingSurfaces = \[\]/);
assert.match(html, /addLandingSurface\(p\.position\.x, p\.position\.z, 4, 20, 6, g\)/);
assert.match(html, /addLandingSurface\(-58, -48, 27, 27, 1\.2, nuclear\)/);
assert.match(html, /addObstacle\(ARCADE_POS\.x \+ i \* 4\.5, ARCADE_POS\.z - 5\.5, 2\.2, \.75, 2\.5\)/);
assert.match(html, /addObstacle\(-58, -48, 8\.6, 8\.6, 8\.8\)/);
assert.match(html, /Superficies altas de objetos/);
console.log('arcade open plaza: ok');
